version: 2

sources:
  - name: justin_raw
    database: postgres  
    schema: etl  
    tables:
      - name: justin_participants
      - name: justin_participant_profiles

models:
  - name: justin_participants
  - name: justin_participants_users